name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code  # Шаг для клонирования репозитория
      uses: actions/checkout@v2

    - name: Set up Python  # Шаг для установки Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Указываем, что нам нужна версия Python 3.x

    - name: Install dependencies  # Шаг для установки зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        chmod +x wait-for-it.sh

    - name: Run Django tests  # Шаг для запуска тестов Django
      run: |
        python manage.py test

    - name: Build and push Docker image  # Шаг для создания и публикации Docker-образа
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}  # Загружаем переменные окружения из Secrets
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        docker-compose -f docker-compose.yml up -d 
        docker tag myproject $DOCKER_USERNAME/myproject  # Тегируем образ перед публикацией
        docker push $DOCKER_USERNAME/myproject  # Публикуем образ на Docker Hub или другой реестр Docker
