name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code  # Шаг для клонирования репозитория
      uses: actions/checkout@v2

    - name: Set up Python  # Шаг для установки Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Указываем, что нам нужна версия Python 3.x

    - name: Install dependencies  # Шаг для установки зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        chmod +x wait-for-it.sh

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Compose
      run: |
        sudo docker compose up -d

    - name: Run Django tests  # Шаг для запуска тестов Django
      run: |
        python manage.py test
        
    - name: Down Docker Compose
      run: |
        sudo docker compose down
